In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('data/corona_tested_individuals_ver_006.english.csv')
print(df.shape)
df.head()

(278848, 10)

/var/folders/_9/sr4c36qx7hbggrnnvqjvqwvc0000gn/T/ipykernel_42413/3189383527.py:1: DtypeWarning: Columns (1,2,3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/corona_tested_individuals_ver_006.english.csv')

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
0,2020-04-30,0,0,0,0,0,negative,None,female,Other
1,2020-04-30,1,0,0,0,0,negative,None,female,Other
2,2020-04-30,0,1,0,0,0,negative,None,male,Other
3,2020-04-30,1,0,0,0,0,negative,None,female,Other
4,2020-04-30,1,0,0,0,0,negative,None,male,Other

In [3]:
df = df.loc[df['corona_result'].ne('other')]
df = df.loc[df['age_60_and_above'].ne('None')]
df = df.loc[df['gender'].ne('None')]
print(df['corona_result'].unique())
print(df['age_60_and_above'].unique())
print(df['gender'].unique())

['negative' 'positive']
['Yes' 'No']
['male' 'female']

In [4]:
labelencoder = LabelEncoder()
df['corona_result'] = labelencoder.fit_transform(df['corona_result'])
df['age_60_and_above'] = labelencoder.fit_transform(df['age_60_and_above'])
df['gender'] = labelencoder.fit_transform(df['gender'])
df.loc[df['cough'] == 'None', "cough"] = 0
df.loc[df['fever'] == 'None', "fever"] = 0
df.loc[df['test_indication'] == 'Contact with confirmed', "test_indication"] = 1
df.loc[df['test_indication'] == 'Other', "test_indication"] = 0
df.loc[df['test_indication'] == 'Abroad', "test_indication"] = 0
df.head()

,test_date,cough,fever,sore_throat,shortness_of_breath,head_ache,corona_result,age_60_and_above,gender,test_indication
122808,2020-04-14,1,0,0,0,0,0,1,1,0
122809,2020-04-14,1,0,0,0,0,1,0,0,0
122810,2020-04-14,0,0,0,0,0,0,0,0,0
122811,2020-04-14,0,1,0,0,0,0,0,0,0
122812,2020-04-14,1,0,0,0,0,0,1,0,0

In [5]:
df.to_csv('data/corona_tested_individuals_ver_006.english_cleaned.csv')